from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
import subprocess

from .models import Evidence, Hypothesis


@dataclass(frozen=True)
class ExecutionResult:
    experiment_id: str
    target: str
    command: tuple[str, ...]
    exit_code: int
    passed: bool
    stdout: str
    stderr: str


@dataclass(frozen=True)
class ExperimentOutcome:
    hypothesis: Hypothesis
    vulnerable: ExecutionResult
    patched: ExecutionResult
    evidence: tuple[Evidence, ...]


def generate_access_control_test(hypothesis: Hypothesis, target_import: str, target_type: str, output_path: str | Path) -> Path:
    """Generate a minimal Foundry security test from an access-control hypothesis."""
    if hypothesis.invariant_id != "INV-AUTH-001":
        raise ValueError(f"Unsupported invariant for Foundry generation: {hypothesis.invariant_id}")
    path = Path(output_path)
    path.parent.mkdir(parents=True, exist_ok=True)
    source = f'''// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.20;

import {{Test}} from "forge-std/Test.sol";
import {{ {target_type} }} from "{target_import}";

/// Generated by CYDRA from {hypothesis.hypothesis_id}.
/// Security invariant: an arbitrary external caller must not mutate privileged state.
contract CydraAuthInvariantTest is Test {{
    {target_type} internal target;
    address internal attacker = address(0xBEEF);
    address internal account = address(0xCAFE);

    function setUp() public {{
        target = new {target_type}();
    }}

    function testUnauthorizedCallerCannotMutatePrivilegedState() public {{
        assertFalse(target.whiteList(account));
        vm.expectRevert();
        vm.prank(attacker);
        target.setWhitelist(account, true);
        assertFalse(target.whiteList(account));
    }}
}}
'''
    path.write_text(source, encoding="utf-8")
    return path


def run_foundry_test(project_dir: str | Path, test_path: str | Path, experiment_id: str, target: str) -> ExecutionResult:
    """Run one generated Foundry test and preserve the complete execution record."""
    project = Path(project_dir)
    relative_test = Path(test_path)
    if relative_test.is_absolute():
        relative_test = relative_test.relative_to(project)
    command = ("forge", "test", "--match-path", str(relative_test), "-vv")
    completed = subprocess.run(command, cwd=project, text=True, capture_output=True, check=False)
    return ExecutionResult(experiment_id, target, command, completed.returncode, completed.returncode == 0, completed.stdout, completed.stderr)


def classify_access_control_outcome(hypothesis: Hypothesis, vulnerable: ExecutionResult, patched: ExecutionResult) -> ExperimentOutcome:
    """Confirm only when vulnerable fails the security test and patched passes it."""
    if not vulnerable.passed and patched.passed:
        status = "confirmed"
    elif vulnerable.passed and not patched.passed:
        status = "rejected"
    else:
        status = "proposed"
    updated = Hypothesis(
        hypothesis_id=hypothesis.hypothesis_id,
        claim=hypothesis.claim,
        invariant_id=hypothesis.invariant_id,
        target_function=hypothesis.target_function,
        attacker_capability=hypothesis.attacker_capability,
        expected_impact=hypothesis.expected_impact,
        status=status,
        evidence_ids=hypothesis.evidence_ids + (
            f"E-EXEC-{hypothesis.hypothesis_id}-VULNERABLE",
            f"E-EXEC-{hypothesis.hypothesis_id}-PATCHED",
        ),
    )
    evidence = (
        Evidence(
            evidence_id=f"E-EXEC-{hypothesis.hypothesis_id}-VULNERABLE",
            kind="execution",
            claim=f"Foundry security test against vulnerable target exited {vulnerable.exit_code}; passed={vulnerable.passed}.",
            source=" ".join(vulnerable.command),
            location=vulnerable.target,
        ),
        Evidence(
            evidence_id=f"E-EXEC-{hypothesis.hypothesis_id}-PATCHED",
            kind="execution",
            claim=f"Foundry security test against patched target exited {patched.exit_code}; passed={patched.passed}.",
            source=" ".join(patched.command),
            location=patched.target,
        ),
    )
    return ExperimentOutcome(updated, vulnerable, patched, evidence)
